#!/bin/sh

sway_command=$1
shift

"$@" &
prog_pid=$!

swaymsg -t subscribe '["window"]' |
    jq --unbuffered --argjson pid "$prog_pid" '.container | select(.pid == $pid).id' | {
    read -r id
    swaymsg "[con_id=$id] $sway_command"
} &
sub_pid=$!

wait $prog_pid
ret=$?

kill $sub_pid

exit $ret