#!/bin/sh

active=$(pacmd list-sources | awk 'c&&!--c;/* index*/{c=1}' | awk '{gsub(/<|>/,"",$0); print $NF}')

filename=$(date +%F_%T.mkv)

# echo active sink: $active 
# echo $filename
status=''
if [[ $1 == "print" ]];then
	# {"text": "$text", "alt": "$alt", "tooltip": "$tooltip", "class": "$class", "percentage": $percentage }
	echo '{"text":"","alt":"Recording","tooltip":"tooltip","class":"record"}' 
	exit 0
fi
if [[ -z $(pgrep wf-recorder) ]];then
	dunstify "Recording Started" -r 688 -i none -a arch
	if [[ "$1" == "-s" ]];then
		echo 1
		wf-recorder -f $HOME/Videos/Recordings/$filename -a "$active" -g "$(slurp -c "#FFFFFF")" >/dev/null 2>&1 &
		sleep 2 
		while [ ! -z $(pgrep -x slurp) ]; do wait; done
		pkill -RTMIN+8 waybar
	elif [[ "$1" == "-w" ]];then
		echo 2
		wf-recorder -f $HOME/Videos/Recordings/$filename -a "$active" -g "$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -c "#FFFFFF" )" >/dev/null 2>&1 &
		sleep 2
		while [ ! -z $(pgrep -x slurp) ]; do wait; done
		pkill -RTMIN+8 waybar
	else
		wf-recorder -f $HOME/Videos/Recordings/$filename -a "$active" >/dev/null 2>&1 &
		pkill -RTMIN+8 waybar
	fi
	echo '{"status": 5}' | jq --unbuffered --compact-output
else
	killall -s SIGINT wf-recorder
	dunstify "Recording Complete" -r 688 -i none -a arch
	while [ ! -z $(pgrep -x wf-recorder) ]; do wait; done
	pkill -RTMIN+8 waybar
	# name="$(zenity --entry --text "enter a filename")"
	perl-rename "s/\.(mkv|mp4)$/ $name $&/" $(ls -d $HOME/Videos/Recordings/* -t | head -n1)
fi