#!/bin/sh
num="$(i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2)"
#a=(${num[0]})
#b=${a[0]}
#echo $a
if [[ $num -eq 1 ]]
then
  echo ""
elif [[ $num -eq 2 ]]
then
  echo ""
elif [[ $num -eq 3 ]]
then
  echo ""
elif [[ $num -eq 4 ]]
then
  echo ""
elif [[ $num -eq 5 ]]
then
  echo ""
elif [[ $num -eq 11 ]]
then
  echo ""
fi